### ISSUE TITLE
Headlines page for Conison Community Centre shows the min generated as 'NaN'

### ISSUE THREAD

**Issue by scrambledleek** [spiraledgeuk/bec#13]
The headlines page for Coniston Community Centre shows the worst day of generation as 'NaN' kWh.  This needs fixing as it is on the display we have installed on-site.

Consider whether we should filter out days with 0 generation when showing the worst day of generation as we probably want to show the lowest amount generated on a day when the system was working.

**Comment by timbarkerSE** [comment]
Fixed handling of zero in sigFigs filter.
