### ISSUE TITLE
Add ways to control the date range and resolution of data for graphs and headlines using the URL

### ISSUE THREAD

**Issue by scrambledleek** [spiraledgeuk/bec#14]
For the graph and headline site views we can currently add "?fullscreen" to the URL to navigate straight to the full-screen version of the page.  This is used by the slide-show 'web-app' which is used on our Raspberry Pis installed in community buildings.

Currently there does not seem to be a way to control the date-range or the resolution of the data graphed or put into a headlines page.

It would be nice to be able to add parameters such as "&days=4", "&weeks=2" or "&months=3" to specify the number of days, weeks or months of data to use and, for the graphs, "&resolution=PT30M", "&resolution=PT1H", "&resolution=P1D", "&resolution=P1W", or  "&resolution=P1M" to select the width of each bar in the chart (from half-hourly to monthly, or just all of the resolutions supported by the QuantitiesService).

**Comment by timbarkerSE** [comment]
Added handling of standard params through query string. Also support for 'days', 'months' and 'weeks'
